version: '3'

services:
  app:
    depends_on:
      - db
    build:
      context: .
    container_name: vuln-info-api
    volumes:
      - ./.data/app:/app:z
    network_mode: "host"
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: mysql:latest
    container_name: vuln-info-db
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    network_mode: "host"
    volumes:
      - ./.data/db:/var/lib/mysql:z
volumes:
  db:
  app: